name: Daily SHRAP Tag Monitor

on:
  workflow_dispatch:  # 只保留手动触发
    inputs:
      disabled:
        description: 'This workflow is disabled'
        required: false

jobs:
  monitor:
    runs-on: ubuntu-latest

    env:
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_CHAT_ID:   ${{ secrets.TG_CHAT_ID }}
      # 若你有代理，可在仓库 Secrets 里加 HTTP_PROXY，再取消注释：
      # http_proxy:  ${{ secrets.HTTP_PROXY }}
      # https_proxy: ${{ secrets.HTTP_PROXY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (lock versions)
        run: |
          pip install httpx playwright undetected-chromedriver selenium selenium-wire requests requests_html webdriver-manager "blinker<1.5" lxml_html_clean
          playwright install chromium

      - name: Run monitor script
        run: |
          python check_shrap_tags.py
