name: Daily SHRAP Tag Monitor

on:
  schedule:
    # 北京 09:00
    - cron: '0 1 * * *'
    # 北京 21:00
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    env:
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_CHAT_ID:   ${{ secrets.TG_CHAT_ID }}
      # 若你有代理，可在仓库 Secrets 里加 HTTP_PROXY，再取消注释：
      # http_proxy:  ${{ secrets.HTTP_PROXY }}
      # https_proxy: ${{ secrets.HTTP_PROXY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (lock versions)
        run: |
          pip install undetected-chromedriver selenium selenium-wire requests webdriver-manager "blinker<1.5"

      - name: Network check (Anycast IP)
        run: |
          echo "Checking reachability to Anycast IP…"
          curl -Iv --connect-timeout 10 https://104.17.8.22/_ping \
            -H "Host: pr.oxylabs.io" || echo "❌ Anycast IP blocked"

      - name: Run monitor script
        run: |
          python check_shrap_tags.py
